"use client";
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import NextAuthSessionProvider from '@/providers/sessionProvider';

const client = new QueryClient;

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin']
})

// export const metadata: Metadata = {
//   title: 'Minhas contas',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <QueryClientProvider client={client}>
          <body className={`${roboto.className} w-screen h-screen overflow-x-hidden bg-gray-700`}>
            <main className='px-0 md:px-6 py-6'>
              {children}
            </main>
            <ToastContainer />
          </body>
        </QueryClientProvider>
      </NextAuthSessionProvider>
    </html>
  )
}
